---
title: "WritingExercise03"
---

# Instructions

In this writing exercise, you will be trying to improve the provided writing sample for logical flow and paragraph structure. Keep in mind Strunk & White's Principles of Composition (particularly, "Make the paragraph the unit of composition") and the suggested structure for explaining scientific experiments (aim-method-result-significance).

Remember that you should use the "commit" process to save your changes. 

# Writing Sample to Edit

Streptomyces are Gram-positive bacteria commonly isolated from soil, marine sediments, or symbiotic associations with invertebrates such as leaf-cutter ants or beewolves which naturally produce a wide range of "secondary metabolites" (natural products), often have anti-cancer, anti-fungal, anti-bacterial properties.
Streptomyces have large, complex genomes with a high-GC content and an unusual structure (linear chromosomes that are typically 8-10 Mbp in length, often containing one or more linear plasmids). 
Classic examples of Streptomyces antibiotic production include Streptomycin by Streptomyces griseus, chloramphenicol by Streptomyces venezuelae, and neomycin by Streptomyces fradiae. 
Analysis has shown that most strains have the capability to produce 20-30 different natural products. 
However, most strains produce only a small number of antibiotics when grown in laboratory culture, raising the following questions: 
1) what are the ecological role(s) of these antibiotics, 
2) what conditions do Streptomyces produce the cryptic metabolites, not produced in normal lab culture
3) can Streptomyces be induced to produce these cryptic metabolites, are they useful as clinically useful antibiotics 
4) how widely transferred these antibiotic biosynthesis gene clusters are amongst different strains of Streptomyces. 

Identifying novel antibiotics is one of many tools that must be employed in order to combat the rising problem of antimicrobial resistance (AMR). Currently, over one million deaths per year can be directly attributed to AMR, with nearly 5 million more deaths that involve AMR as a contributing factor. 
The emergence of multidrug-resistant (MDR) organisms thus threatens the United Nations Sustainable Development Goal (UN SDG) 3. 
Treatment with small molecules including siderophores and gamma-butyrolactones, genetic manipulations (including overexpression of global regulators or pathway-specific activators), and genetic engineering of the host strain transcriptional/translational machinery (e.g., introduction of "Ochi mutations" in rpsL and rpoB), can activate expression of previously cryptic gene clusters in Streptomyces species. 
In this work, we will test whether addition of NAG is able to induce the production of novel antibiotics in a newly isolated species of Streptomyces (S. strathclydensis). 

Future work should investigate whether key pathogens (ESKAPE pathogens) can easily evolve resistanceu sing a combination of bioassay-guided fractionation and chemical characterization methods.


