---
title: "WritingExercise05"
---

# Reflect on your own skills and development as a writer

- What are the areas you think you are good at? Where can you improve?
I think I do well at omitting unneccesary words. I need to improve on rearranging and determining the flow of paragraphs as I struggled a little on exercise 4.

- How will you further develop your skills over the coming year? Can you make a specific, detailed plan?
I can develop my skills by reading more scientific papers to expose myself to the structure and vocabulary use dby scientists to enable the pitching of scientific content, reading at least one scoentific paper a month and really analysing the wording, also going through more of the exercises to make sure I retain the skills needed to be able to wreite a good scientific paper to effectively convey my findings to readers.
# Reflect on writing more generally

- What principles of composition discussed today did you find most useful?
The grammar task and cutting down unneccesary words task
- If you were going to formulate your own writing rules, what would they be?
Start with broad general topic description continue with explanantions, using why, how, who, what answering all of these questions and bringing back the topic aim of the report not forgetting to address the problem and the reason of why the experiemtn is carried out to let the readers fully understand the reasoning behind the writing.

# Commit your reflections to writing

Compose a paragraph summarizing your reflections. Remember to use the "commit" process to save your changes when you are finished.
